

version: '3.6'

services:

    qlmuxd:
        #build: .
        container_name: qlmuxd
        image: qlmuxd
        hostname: qlmuxd
        volumes:
            - ./qlmux/qlmuxd.cfg:/usr/local/etc/qlmuxd.cfg
        environment:
            PYTHONUNBUFFERED: 1
